In [1]:
!mysql < /home/jupyter/mp/snippets/sakila/sakila-database.sql

In [2]:
!mysql < /home/jupyter/mp/snippets/sakila/sakila-data.sql

In [3]:
!mysql sakila -e "show tables"

+----------------------------+
| Tables_in_sakila           |
+----------------------------+
| actor                      |
| actor_info                 |
| address                    |
| category                   |
| city                       |
| country                    |
| customer                   |
| customer_list              |
| film                       |
| film_actor                 |
| film_category              |
| film_list                  |
| film_text                  |
| inventory                  |
| language                   |
| nicer_but_slower_film_list |
| payment                    |
| rental                     |
| sales_by_film_category     |
| sales_by_store             |
| staff                      |
| staff_list                 |
| store                      |
+----------------------------+

In [4]:
!mysql sakila -e "select count(*) from actor"

+----------+
| count(*) |
+----------+
|      200 |
+----------+

In [5]:
!mysql sakila -e "select count(*) from actor_info"

+----------+
| count(*) |
+----------+
|      200 |
+----------+

In [6]:
!mysql sakila -e "select count(*) from address"

+----------+
| count(*) |
+----------+
|      603 |
+----------+

In [7]:
!mysql sakila -e "select count(*) from category"

+----------+
| count(*) |
+----------+
|       16 |
+----------+

In [8]:
!mysql sakila -e "select count(*) from city"

+----------+
| count(*) |
+----------+
|      600 |
+----------+

In [9]:
!mysql sakila -e "select count(*) from country"

+----------+
| count(*) |
+----------+
|      109 |
+----------+

In [10]:
!mysql sakila -e "select count(*) from customer"

+----------+
| count(*) |
+----------+
|      599 |
+----------+

In [11]:
!mysql sakila -e "select count(*) from customer_list"

+----------+
| count(*) |
+----------+
|      599 |
+----------+

In [12]:
!mysql sakila -e "select count(*) from film"

+----------+
| count(*) |
+----------+
|     1000 |
+----------+

In [13]:
!mysql sakila -e "select count(*) from film_actor"

+----------+
| count(*) |
+----------+
|     5462 |
+----------+

In [14]:
!mysql sakila -e "select count(*) from film_category"

+----------+
| count(*) |
+----------+
|     1000 |
+----------+

In [15]:
!mysql sakila -e "select count(*) from film_list"

+----------+
| count(*) |
+----------+
|      997 |
+----------+

In [16]:
!mysql sakila -e "select count(*) from film_text"

+----------+
| count(*) |
+----------+
|     1000 |
+----------+

In [17]:
!mysql sakila -e "select count(*) from inventory"

+----------+
| count(*) |
+----------+
|     4581 |
+----------+

In [18]:
!mysql sakila -e "select count(*) from language"

+----------+
| count(*) |
+----------+
|        6 |
+----------+

In [19]:
!mysql sakila -e "select count(*) from nicer_but_slower_film_list"

+----------+
| count(*) |
+----------+
|      997 |
+----------+

In [20]:
!mysql sakila -e "select count(*) from payment"

+----------+
| count(*) |
+----------+
|    16049 |
+----------+

In [21]:
!mysql sakila -e "select count(*) from rental"

+----------+
| count(*) |
+----------+
|    16044 |
+----------+

In [22]:
!mysql sakila -e "select count(*) from sales_by_film_category"

+----------+
| count(*) |
+----------+
|       16 |
+----------+

In [23]:
!mysql sakila -e "select count(*) from sales_by_store"

+----------+
| count(*) |
+----------+
|        2 |
+----------+

In [24]:
!mysql sakila -e "select count(*) from staff"

+----------+
| count(*) |
+----------+
|        2 |
+----------+

In [25]:
!mysql sakila -e "select count(*) from staff_list"

+----------+
| count(*) |
+----------+
|        2 |
+----------+

In [26]:
!mysql sakila -e "select count(*) from store"

+----------+
| count(*) |
+----------+
|        2 |
+----------+

In [30]:
!mysql sakila -e "select * from actor limit 5"

+----------+------------+--------------+---------------------+
| actor_id | first_name | last_name    | last_update         |
+----------+------------+--------------+---------------------+
|        1 | PENELOPE   | GUINESS      | 2006-02-15 04:34:33 |
|        2 | NICK       | WAHLBERG     | 2006-02-15 04:34:33 |
|        3 | ED         | CHASE        | 2006-02-15 04:34:33 |
|        4 | JENNIFER   | DAVIS        | 2006-02-15 04:34:33 |
|        5 | JOHNNY     | LOLLOBRIGIDA | 2006-02-15 04:34:33 |
+----------+------------+--------------+---------------------+

In [ ]:
!mysql sakila -e "select * from actor_info limit 5"

+----------+------------+--------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| actor_id | first_name | last_name    | film_info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+----------+------------+--------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|        1 | PENELOPE   | GUINESS      | Animation: ANACONDA CONFESSIONS; Children: LANGUAGE COWBOY; Classics: COLOR PHILADELPHIA, WESTWARD SEABISCUIT; Comedy: VERTIGO NORTHWEST; Documentary: ACADEMY DINOSAUR; Family: KING EVOLUTION, SPLASH GUMP; Foreign: MULHOLLAND BEAST; Games: BULWORTH COMMANDMENTS, HUMAN GRAFFITI; Horror: ELEPHANT TROJAN, LADY STAGE, RULES HUMAN; Music: WIZARD COLDBLOODED; New: ANGELS LIFE, OKLAHOMA JUMANJI; Sci-Fi: CHEAPER CLYDE; Sports: GLEAMING JAWBREAKER                                                                                                                                                             |
|        2 | NICK       | WAHLBERG     | Action: BULL SHAWSHANK; Animation: FIGHT JAWBREAKER; Children: JERSEY SASSY; Classics: DRACULA CRYSTAL, GILBERT PELICAN; Comedy: MALLRATS UNITED, RUSHMORE MERMAID; Documentary: ADAPTATION HOLES; Drama: WARDROBE PHANTOM; Family: APACHE DIVINE, CHISUM BEHAVIOR, INDIAN LOVE, MAGUIRE APACHE; Foreign: BABY HALL, HAPPINESS UNITED; Games: ROOF CHAMPION; Music: LUCKY FLYING; New: DESTINY SATURDAY, FLASH WARS, JEKYLL FROGMEN, MASK PEACH; Sci-Fi: CHAINSAW UPTOWN, GOODFELLAS SALUTE; Travel: LIAISONS SWEET, SMILE EARRING                                                                                     |
|        3 | ED         | CHASE        | Action: CADDYSHACK JEDI, FORREST SONS; Classics: FROST HEAD, JEEPERS WEDDING; Documentary: ARMY FLINTSTONES, FRENCH HOLIDAY, HALLOWEEN NUTS, HUNTER ALTER, WEDDING APOLLO, YOUNG LANGUAGE; Drama: LUCK OPUS, NECKLACE OUTBREAK, SPICE SORORITY; Foreign: COWBOY DOOM, WHALE BIKINI; Music: ALONE TRIP; New: EVE RESURRECTION, PLATOON INSTINCT; Sci-Fi: WEEKEND PERSONAL; Sports: ARTIST COLDBLOODED, IMAGE PRINCESS; Travel: BOONDOCK BALLROOM                                                                                                                                                                        |
|        4 | JENNIFER   | DAVIS        | Action: BAREFOOT MANCHURIAN; Animation: ANACONDA CONFESSIONS, GHOSTBUSTERS ELF; Comedy: SUBMARINE BED; Documentary: BED HIGHBALL, NATIONAL STORY, RAIDERS ANTITRUST; Drama: BLADE POLISH, GREEDY ROOTS; Family: SPLASH GUMP; Horror: TREASURE COMMAND; Music: HANOVER GALAXY, REDS POCUS; New: ANGELS LIFE, JUMANJI BLADE, OKLAHOMA JUMANJI; Sci-Fi: RANDOM GO, SILVERADO GOLDFINGER, UNFORGIVEN ZOOLANDER; Sports: INSTINCT AIRPORT, POSEIDON FOREVER; Travel: BOONDOCK BALLROOM                                                                                                                                      |
|        5 | JOHNNY     | LOLLOBRIGIDA | Action: AMADEUS HOLY, GRAIL FRANKENSTEIN, RINGS HEARTBREAKERS; Animation: SUNRISE LEAGUE; Children: HALL CASSIDY; Comedy: DADDY PITTSBURGH; Documentary: BONNIE HOLOCAUST, METAL ARMAGEDDON, PACIFIC AMISTAD, POCUS PULP; Drama: CHITTY LOCK, CONEHEADS SMOOCHY; Games: FIRE WOLVES; Horror: COMMANDMENTS EXPRESS, LOVE SUICIDES, PATTON INTERVIEW; Music: BANGER PINOCCHIO, HEAVENLY GUN; New: FRONTIER CABIN, RIDGEMONT SUBMARINE; Sci-Fi: DAISY MENAGERIE, GOODFELLAS SALUTE, SOLDIERS EVOLUTION; Sports: GROOVE FICTION, KRAMER CHOCOLATE, STAR OPERATION; Travel: ENOUGH RAGING, ESCAPE METROPOLIS, SMILE EARRING |
+----------+------------+--------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

In [32]:
!mysql sakila -e "select * from address limit 5"

+------------+----------------------+----------+----------+---------+-------------+-------------+---------------------------+---------------------+
| address_id | address              | address2 | district | city_id | postal_code | phone       | location                  | last_update         |
+------------+----------------------+----------+----------+---------+-------------+-------------+---------------------------+---------------------+
|          1 | 47 MySakila Drive    | NULL     | Alberta  |     300 |             |             |        >
2]c4\�vۍ��H@     | 2014-09-25 22:30:27 |
|          2 | 28 MySQL Boulevard   | NULL     | QLD      |     576 |             |             |        ��߁$c@N��P"�;�        | 2014-09-25 22:30:09 |
|          3 | 23 Workhaven Lane    | NULL     | Alberta  |     300 |             | 14033335568 |        ��hc4\��~p��H@       | 2014-09-25 22:30:27 |
�4&c@B֮d"�;�     | 2014-09-25 22:30:09 |L     | QLD      |     576 |             | 6172235589  |        [
|          5 | 1913 Hanoi Way       |          | Nagasaki |     463 | 35200       | 28303384290 |        (�7!7`@����_�@@       | 2014-09-25 22:31:53 |
+------------+----------------------+----------+----------+---------+-------------+-------------+---------------------------+---------------------+

In [33]:
!mysql sakila -e "select * from category limit 5"

+-------------+-----------+---------------------+
| category_id | name      | last_update         |
+-------------+-----------+---------------------+
|           1 | Action    | 2006-02-15 04:46:27 |
|           2 | Animation | 2006-02-15 04:46:27 |
|           3 | Children  | 2006-02-15 04:46:27 |
|           4 | Classics  | 2006-02-15 04:46:27 |
|           5 | Comedy    | 2006-02-15 04:46:27 |
+-------------+-----------+---------------------+

In [34]:
!mysql sakila -e "select * from city limit 5"

+---------+--------------------+------------+---------------------+
| city_id | city               | country_id | last_update         |
+---------+--------------------+------------+---------------------+
|       1 | A Corua (La Corua) |         87 | 2006-02-15 04:45:25 |
|       2 | Abha               |         82 | 2006-02-15 04:45:25 |
|       3 | Abu Dhabi          |        101 | 2006-02-15 04:45:25 |
|       4 | Acua               |         60 | 2006-02-15 04:45:25 |
|       5 | Adana              |         97 | 2006-02-15 04:45:25 |
+---------+--------------------+------------+---------------------+

In [35]:
!mysql sakila -e "select * from country limit 5"

+------------+----------------+---------------------+
| country_id | country        | last_update         |
+------------+----------------+---------------------+
|          1 | Afghanistan    | 2006-02-15 04:44:00 |
|          2 | Algeria        | 2006-02-15 04:44:00 |
|          3 | American Samoa | 2006-02-15 04:44:00 |
|          4 | Angola         | 2006-02-15 04:44:00 |
|          5 | Anguilla       | 2006-02-15 04:44:00 |
+------------+----------------+---------------------+

In [36]:
!mysql sakila -e "select * from customer limit 5"

+-------------+----------+------------+-----------+-------------------------------------+------------+--------+---------------------+---------------------+
| customer_id | store_id | first_name | last_name | email                               | address_id | active | create_date         | last_update         |
+-------------+----------+------------+-----------+-------------------------------------+------------+--------+---------------------+---------------------+
|           1 |        1 | MARY       | SMITH     | MARY.SMITH@sakilacustomer.org       |          5 |      1 | 2006-02-14 22:04:36 | 2006-02-15 04:57:20 |
|           2 |        1 | PATRICIA   | JOHNSON   | PATRICIA.JOHNSON@sakilacustomer.org |          6 |      1 | 2006-02-14 22:04:36 | 2006-02-15 04:57:20 |
|           3 |        1 | LINDA      | WILLIAMS  | LINDA.WILLIAMS@sakilacustomer.org   |          7 |      1 | 2006-02-14 22:04:36 | 2006-02-15 04:57:20 |
|           4 |        2 | BARBARA    | JONES     | BARBARA.JONES@sakilacustomer.org    |          8 |      1 | 2006-02-14 22:04:36 | 2006-02-15 04:57:20 |
|           5 |        1 | ELIZABETH  | BROWN     | ELIZABETH.BROWN@sakilacustomer.org  |          9 |      1 | 2006-02-14 22:04:36 | 2006-02-15 04:57:20 |
+-------------+----------+------------+-----------+-------------------------------------+------------+--------+---------------------+---------------------+

In [37]:
!mysql sakila -e "select * from customer_list limit 5"

+-----+----------------+-----------------------------+----------+--------------+--------+----------------+--------+-----+
| ID  | name           | address                     | zip code | phone        | city   | country        | notes  | SID |
+-----+----------------+-----------------------------+----------+--------------+--------+----------------+--------+-----+
| 218 | VERA MCCOY     | 1168 Najafabad Parkway      | 40301    | 886649065861 | Kabul  | Afghanistan    | active |   1 |
| 441 | MARIO CHEATHAM | 1924 Shimonoseki Drive      | 52625    | 406784385440 | Batna  | Algeria        | active |   1 |
|  69 | JUDY GRAY      | 1031 Daugavpils Parkway     | 59025    | 107137400143 | Bchar  | Algeria        | active |   2 |
| 176 | JUNE CARROLL   | 757 Rustenburg Avenue       | 89668    | 506134035434 | Skikda | Algeria        | active |   1 |
| 320 | ANTHONY SCHWAB | 1892 Nabereznyje Telny Lane | 28396    | 478229987054 | Tafuna | American Samoa | active |   2 |
+-----+----------------+-----------------------------+----------+--------------+--------+----------------+--------+-----+

In [38]:
!mysql sakila -e "select * from film limit 5"

+---------+------------------+-----------------------------------------------------------------------------------------------------------------------+--------------+-------------+----------------------+-----------------+-------------+--------+------------------+--------+----------------------------------+---------------------+
| film_id | title            | description                                                                                                           | release_year | language_id | original_language_id | rental_duration | rental_rate | length | replacement_cost | rating | special_features                 | last_update         |
+---------+------------------+-----------------------------------------------------------------------------------------------------------------------+--------------+-------------+----------------------+-----------------+-------------+--------+------------------+--------+----------------------------------+---------------------+
|       1 | ACADEMY DINOSAUR | A Epic Drama of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies                      |         2006 |           1 |                 NULL |               6 |        0.99 |     86 |            20.99 | PG     | Deleted Scenes,Behind the Scenes | 2006-02-15 05:03:42 |
|       2 | ACE GOLDFINGER   | A Astounding Epistle of a Database Administrator And a Explorer who must Find a Car in Ancient China                  |         2006 |           1 |                 NULL |               3 |        4.99 |     48 |            12.99 | G      | Trailers,Deleted Scenes          | 2006-02-15 05:03:42 |
|       3 | ADAPTATION HOLES | A Astounding Reflection of a Lumberjack And a Car who must Sink a Lumberjack in A Baloon Factory                      |         2006 |           1 |                 NULL |               7 |        2.99 |     50 |            18.99 | NC-17  | Trailers,Deleted Scenes          | 2006-02-15 05:03:42 |
|       4 | AFFAIR PREJUDICE | A Fanciful Documentary of a Frisbee And a Lumberjack who must Chase a Monkey in A Shark Tank                          |         2006 |           1 |                 NULL |               5 |        2.99 |    117 |            26.99 | G      | Commentaries,Behind the Scenes   | 2006-02-15 05:03:42 |
|       5 | AFRICAN EGG      | A Fast-Paced Documentary of a Pastry Chef And a Dentist who must Pursue a Forensic Psychologist in The Gulf of Mexico |         2006 |           1 |                 NULL |               6 |        2.99 |    130 |            22.99 | G      | Deleted Scenes                   | 2006-02-15 05:03:42 |
+---------+------------------+-----------------------------------------------------------------------------------------------------------------------+--------------+-------------+----------------------+-----------------+-------------+--------+------------------+--------+----------------------------------+---------------------+

In [39]:
!mysql sakila -e "select * from film_actor limit 5"

+----------+---------+---------------------+
| actor_id | film_id | last_update         |
+----------+---------+---------------------+
|        1 |       1 | 2006-02-15 05:05:03 |
|        1 |      23 | 2006-02-15 05:05:03 |
|        1 |      25 | 2006-02-15 05:05:03 |
|        1 |     106 | 2006-02-15 05:05:03 |
|        1 |     140 | 2006-02-15 05:05:03 |
+----------+---------+---------------------+

In [40]:
!mysql sakila -e "select * from film_category limit 5"

+---------+-------------+---------------------+
| film_id | category_id | last_update         |
+---------+-------------+---------------------+
|       1 |           6 | 2006-02-15 05:07:09 |
|       2 |          11 | 2006-02-15 05:07:09 |
|       3 |           6 | 2006-02-15 05:07:09 |
|       4 |          11 | 2006-02-15 05:07:09 |
|       5 |           8 | 2006-02-15 05:07:09 |
+---------+-------------+---------------------+

In [41]:
!mysql sakila -e "select * from film_list limit 5"

+------+------------------+-----------------------------------------------------------------------------------------------------------------------+-------------+-------+--------+--------+------------------------------------------------------------------------------------------------------------------------------------------------+
| FID  | title            | description                                                                                                           | category    | price | length | rating | actors                                                                                                                                         |
+------+------------------+-----------------------------------------------------------------------------------------------------------------------+-------------+-------+--------+--------+------------------------------------------------------------------------------------------------------------------------------------------------+
|    1 | ACADEMY DINOSAUR | A Epic Drama of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies                      | Documentary |  0.99 |     86 | PG     | PENELOPE GUINESS, LUCILLE TRACY, SANDRA PECK, JOHNNY CAGE, MENA TEMPLE, WARREN NOLTE, OPRAH KILMER, ROCK DUKAKIS, MARY KEITEL, CHRISTIAN GABLE |
|    2 | ACE GOLDFINGER   | A Astounding Epistle of a Database Administrator And a Explorer who must Find a Car in Ancient China                  | Horror      |  4.99 |     48 | G      | CHRIS DEPP, SEAN GUINESS, MINNIE ZELLWEGER, BOB FAWCETT                                                                                        |
|    3 | ADAPTATION HOLES | A Astounding Reflection of a Lumberjack And a Car who must Sink a Lumberjack in A Baloon Factory                      | Documentary |  2.99 |     50 | NC-17  | NICK WAHLBERG, BOB FAWCETT, CAMERON STREEP, RAY JOHANSSON, JULIANNE DENCH                                                                      |
|    4 | AFFAIR PREJUDICE | A Fanciful Documentary of a Frisbee And a Lumberjack who must Chase a Monkey in A Shark Tank                          | Horror      |  2.99 |    117 | G      | OPRAH KILMER, FAY WINSLET, KENNETH PESCI, SCARLETT DAMON, JODIE DEGENERES                                                                      |
|    5 | AFRICAN EGG      | A Fast-Paced Documentary of a Pastry Chef And a Dentist who must Pursue a Forensic Psychologist in The Gulf of Mexico | Family      |  2.99 |    130 | G      | DUSTIN TAUTOU, GARY PHOENIX, MATTHEW CARREY, MATTHEW LEIGH, THORA TEMPLE                                                                       |
+------+------------------+-----------------------------------------------------------------------------------------------------------------------+-------------+-------+--------+--------+------------------------------------------------------------------------------------------------------------------------------------------------+

In [43]:
!mysql sakila -e "select * from actor film_text limit 5"

+----------+------------+--------------+---------------------+
| actor_id | first_name | last_name    | last_update         |
+----------+------------+--------------+---------------------+
|        1 | PENELOPE   | GUINESS      | 2006-02-15 04:34:33 |
|        2 | NICK       | WAHLBERG     | 2006-02-15 04:34:33 |
|        3 | ED         | CHASE        | 2006-02-15 04:34:33 |
|        4 | JENNIFER   | DAVIS        | 2006-02-15 04:34:33 |
|        5 | JOHNNY     | LOLLOBRIGIDA | 2006-02-15 04:34:33 |
+----------+------------+--------------+---------------------+

In [44]:
!mysql sakila -e "select * from inventory limit 5"

+--------------+---------+----------+---------------------+
| inventory_id | film_id | store_id | last_update         |
+--------------+---------+----------+---------------------+
|            1 |       1 |        1 | 2006-02-15 05:09:17 |
|            2 |       1 |        1 | 2006-02-15 05:09:17 |
|            3 |       1 |        1 | 2006-02-15 05:09:17 |
|            4 |       1 |        1 | 2006-02-15 05:09:17 |
|            5 |       1 |        2 | 2006-02-15 05:09:17 |
+--------------+---------+----------+---------------------+

In [45]:
!mysql sakila -e "select * from language limit 5"

+-------------+----------+---------------------+
| language_id | name     | last_update         |
+-------------+----------+---------------------+
|           1 | English  | 2006-02-15 05:02:19 |
|           2 | Italian  | 2006-02-15 05:02:19 |
|           3 | Japanese | 2006-02-15 05:02:19 |
|           4 | Mandarin | 2006-02-15 05:02:19 |
|           5 | French   | 2006-02-15 05:02:19 |
+-------------+----------+---------------------+

In [46]:
!mysql sakila -e "select * from nicer_but_slower_film_list limit 5"

+------+------------------+-----------------------------------------------------------------------------------------------------------------------+-------------+-------+--------+--------+------------------------------------------------------------------------------------------------------------------------------------------------+
| FID  | title            | description                                                                                                           | category    | price | length | rating | actors                                                                                                                                         |
+------+------------------+-----------------------------------------------------------------------------------------------------------------------+-------------+-------+--------+--------+------------------------------------------------------------------------------------------------------------------------------------------------+
|    1 | ACADEMY DINOSAUR | A Epic Drama of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies                      | Documentary |  0.99 |     86 | PG     | Penelope Guiness, Lucille Tracy, Sandra Peck, Johnny Cage, Mena Temple, Warren Nolte, Oprah Kilmer, Rock Dukakis, Mary Keitel, Christian Gable |
|    2 | ACE GOLDFINGER   | A Astounding Epistle of a Database Administrator And a Explorer who must Find a Car in Ancient China                  | Horror      |  4.99 |     48 | G      | Chris Depp, Sean Guiness, Minnie Zellweger, Bob Fawcett                                                                                        |
|    3 | ADAPTATION HOLES | A Astounding Reflection of a Lumberjack And a Car who must Sink a Lumberjack in A Baloon Factory                      | Documentary |  2.99 |     50 | NC-17  | Nick Wahlberg, Bob Fawcett, Cameron Streep, Ray Johansson, Julianne Dench                                                                      |
|    4 | AFFAIR PREJUDICE | A Fanciful Documentary of a Frisbee And a Lumberjack who must Chase a Monkey in A Shark Tank                          | Horror      |  2.99 |    117 | G      | Oprah Kilmer, Fay Winslet, Kenneth Pesci, Scarlett Damon, Jodie Degeneres                                                                      |
|    5 | AFRICAN EGG      | A Fast-Paced Documentary of a Pastry Chef And a Dentist who must Pursue a Forensic Psychologist in The Gulf of Mexico | Family      |  2.99 |    130 | G      | Dustin Tautou, Gary Phoenix, Matthew Carrey, Matthew Leigh, Thora Temple                                                                       |
+------+------------------+-----------------------------------------------------------------------------------------------------------------------+-------------+-------+--------+--------+------------------------------------------------------------------------------------------------------------------------------------------------+

In [47]:
!mysql sakila -e "select * from payment limit 5"

+------------+-------------+----------+-----------+--------+---------------------+---------------------+
| payment_id | customer_id | staff_id | rental_id | amount | payment_date        | last_update         |
+------------+-------------+----------+-----------+--------+---------------------+---------------------+
|          1 |           1 |        1 |        76 |   2.99 | 2005-05-25 11:30:37 | 2006-02-15 22:12:30 |
|          2 |           1 |        1 |       573 |   0.99 | 2005-05-28 10:35:23 | 2006-02-15 22:12:30 |
|          3 |           1 |        1 |      1185 |   5.99 | 2005-06-15 00:54:12 | 2006-02-15 22:12:30 |
|          4 |           1 |        2 |      1422 |   0.99 | 2005-06-15 18:02:53 | 2006-02-15 22:12:30 |
|          5 |           1 |        2 |      1476 |   9.99 | 2005-06-15 21:08:46 | 2006-02-15 22:12:30 |
+------------+-------------+----------+-----------+--------+---------------------+---------------------+

In [48]:
!mysql sakila -e "select * from rental limit 5"

+-----------+---------------------+--------------+-------------+---------------------+----------+---------------------+
| rental_id | rental_date         | inventory_id | customer_id | return_date         | staff_id | last_update         |
+-----------+---------------------+--------------+-------------+---------------------+----------+---------------------+
|         1 | 2005-05-24 22:53:30 |          367 |         130 | 2005-05-26 22:04:30 |        1 | 2006-02-15 21:30:53 |
|         2 | 2005-05-24 22:54:33 |         1525 |         459 | 2005-05-28 19:40:33 |        1 | 2006-02-15 21:30:53 |
|         3 | 2005-05-24 23:03:39 |         1711 |         408 | 2005-06-01 22:12:39 |        1 | 2006-02-15 21:30:53 |
|         4 | 2005-05-24 23:04:41 |         2452 |         333 | 2005-06-03 01:43:41 |        2 | 2006-02-15 21:30:53 |
|         5 | 2005-05-24 23:05:21 |         2079 |         222 | 2005-06-02 04:33:21 |        1 | 2006-02-15 21:30:53 |
+-----------+---------------------+--------------+-------------+---------------------+----------+---------------------+

In [49]:
!mysql sakila -e "select * from sales_by_film_category limit 5"

+-----------+-------------+
| category  | total_sales |
+-----------+-------------+
| Sports    |     5314.21 |
| Sci-Fi    |     4756.98 |
| Animation |     4656.30 |
| Drama     |     4587.39 |
| Comedy    |     4383.58 |
+-----------+-------------+

In [50]:
!mysql sakila -e "select * from sales_by_store limit 5"

+---------------------+--------------+-------------+
| store               | manager      | total_sales |
+---------------------+--------------+-------------+
| Woodridge,Australia | Jon Stephens |    33726.77 |
| Lethbridge,Canada   | Mike Hillyer |    33679.79 |
+---------------------+--------------+-------------+

In [54]:
# !mysql sakila -e "select * from staff limit 5"

In [52]:
!mysql sakila -e "select * from staff_list limit 5"

+----+--------------+----------------------+----------+-------------+------------+-----------+-----+
| ID | name         | address              | zip code | phone       | city       | country   | SID |
+----+--------------+----------------------+----------+-------------+------------+-----------+-----+
|  1 | Mike Hillyer | 23 Workhaven Lane    |          | 14033335568 | Lethbridge | Canada    |   1 |
|  2 | Jon Stephens | 1411 Lillydale Drive |          | 6172235589  | Woodridge  | Australia |   2 |
+----+--------------+----------------------+----------+-------------+------------+-----------+-----+

In [53]:
!mysql sakila -e "select * from store limit 5"

+----------+------------------+------------+---------------------+
| store_id | manager_staff_id | address_id | last_update         |
+----------+------------------+------------+---------------------+
|        1 |                1 |          1 | 2006-02-15 04:57:12 |
|        2 |                2 |          2 | 2006-02-15 04:57:12 |
+----------+------------------+------------+---------------------+

In [55]:
# this query takes the city table and orders the cities by their country ID instead of city ID
!mysql sakila -e "select * from city order by country_id"

+---------+----------------------------+------------+---------------------+
| city_id | city                       | country_id | last_update         |
+---------+----------------------------+------------+---------------------+
|     251 | Kabul                      |          1 | 2006-02-15 04:45:25 |
|      59 | Batna                      |          2 | 2006-02-15 04:45:25 |
|      63 | Bchar                      |          2 | 2006-02-15 04:45:25 |
|     483 | Skikda                     |          2 | 2006-02-15 04:45:25 |
|     516 | Tafuna                     |          3 | 2006-02-15 04:45:25 |
|      67 | Benguela                   |          4 | 2006-02-15 04:45:25 |
|     360 | Namibe                     |          4 | 2006-02-15 04:45:25 |
|     493 | South Hill                 |          5 | 2006-02-15 04:45:25 |
|      20 | Almirante Brown            |          6 | 2006-02-15 04:45:25 |
|      43 | Avellaneda                 |          6 | 2006-02-15 04:45:25 |
|      45 | Baha Blanca                |          6 | 2006-02-15 04:45:25 |
|     128 | Crdoba                     |          6 | 2006-02-15 04:45:25 |
|     161 | Escobar                    |          6 | 2006-02-15 04:45:25 |
|     165 | Ezeiza                     |          6 | 2006-02-15 04:45:25 |
|     289 | La Plata                   |          6 | 2006-02-15 04:45:25 |
|     334 | Merlo                      |          6 | 2006-02-15 04:45:25 |
|     424 | Quilmes                    |          6 | 2006-02-15 04:45:25 |
|     454 | San Miguel de Tucumn       |          6 | 2006-02-15 04:45:25 |
|     457 | Santa F                    |          6 | 2006-02-15 04:45:25 |
|     524 | Tandil                     |          6 | 2006-02-15 04:45:25 |
|     567 | Vicente Lpez               |          6 | 2006-02-15 04:45:25 |
|     586 | Yerevan                    |          7 | 2006-02-15 04:45:25 |
|     576 | Woodridge                  |          8 | 2006-02-15 04:45:25 |
|     186 | Graz                       |          9 | 2006-02-15 04:45:25 |
|     307 | Linz                       |          9 | 2006-02-15 04:45:25 |
|     447 | Salzburg                   |          9 | 2006-02-15 04:45:25 |
|      48 | Baku                       |         10 | 2006-02-15 04:45:25 |
|     505 | Sumqayit                   |         10 | 2006-02-15 04:45:25 |
|      14 | al-Manama                  |         11 | 2006-02-15 04:45:25 |
|     143 | Dhaka                      |         12 | 2006-02-15 04:45:25 |
|     234 | Jamalpur                   |         12 | 2006-02-15 04:45:25 |
|     525 | Tangail                    |         12 | 2006-02-15 04:45:25 |
|     339 | Mogiljov                   |         13 | 2006-02-15 04:45:25 |
|     340 | Molodetno                  |         13 | 2006-02-15 04:45:25 |
|     153 | El Alto                    |         14 | 2006-02-15 04:45:25 |
|     501 | Sucre                      |         14 | 2006-02-15 04:45:25 |
|      21 | Alvorada                   |         15 | 2006-02-15 04:45:25 |
|      25 | Angra dos Reis             |         15 | 2006-02-15 04:45:25 |
|      26 | Anpolis                    |         15 | 2006-02-15 04:45:25 |
|      28 | Aparecida de Goinia        |         15 | 2006-02-15 04:45:25 |
|      30 | Araatuba                   |         15 | 2006-02-15 04:45:25 |
|      44 | Bag                        |         15 | 2006-02-15 04:45:25 |
|      66 | Belm                       |         15 | 2006-02-15 04:45:25 |
|      83 | Blumenau                   |         15 | 2006-02-15 04:45:25 |
|      84 | Boa Vista                  |         15 | 2006-02-15 04:45:25 |
|      89 | Braslia                    |         15 | 2006-02-15 04:45:25 |
|     183 | Goinia                     |         15 | 2006-02-15 04:45:25 |
|     189 | Guaruj                     |         15 | 2006-02-15 04:45:25 |
|     190 | guas Lindas de Gois        |         15 | 2006-02-15 04:45:25 |
|     215 | Ibirit                     |         15 | 2006-02-15 04:45:25 |
|     247 | Juazeiro do Norte          |         15 | 2006-02-15 04:45:25 |
|     248 | Juiz de Fora               |         15 | 2006-02-15 04:45:25 |
|     317 | Luzinia                    |         15 | 2006-02-15 04:45:25 |
|     328 | Maring                     |         15 | 2006-02-15 04:45:25 |
|     410 | Po                         |         15 | 2006-02-15 04:45:25 |
|     413 | Poos de Caldas             |         15 | 2006-02-15 04:45:25 |
|     431 | Rio Claro                  |         15 | 2006-02-15 04:45:25 |
|     456 | Santa Brbara dOeste        |         15 | 2006-02-15 04:45:25 |
|     461 | Santo Andr                 |         15 | 2006-02-15 04:45:25 |
|     485 | So Bernardo do Campo       |         15 | 2006-02-15 04:45:25 |
|     486 | So Leopoldo                |         15 | 2006-02-15 04:45:25 |
|     490 | Sorocaba                   |         15 | 2006-02-15 04:45:25 |
|     569 | Vila Velha                 |         15 | 2006-02-15 04:45:25 |
|     572 | Vitria de Santo Anto       |         15 | 2006-02-15 04:45:25 |
|      53 | Bandar Seri Begawan        |         16 | 2006-02-15 04:45:25 |
|     436 | Ruse                       |         17 | 2006-02-15 04:45:25 |
|     498 | Stara Zagora               |         17 | 2006-02-15 04:45:25 |
|      60 | Battambang                 |         18 | 2006-02-15 04:45:25 |
|     406 | Phnom Penh                 |         18 | 2006-02-15 04:45:25 |
|      52 | Bamenda                    |         19 | 2006-02-15 04:45:25 |
|     585 | Yaound                     |         19 | 2006-02-15 04:45:25 |
|     179 | Gatineau                   |         20 | 2006-02-15 04:45:25 |
|     196 | Halifax                    |         20 | 2006-02-15 04:45:25 |
|     300 | Lethbridge                 |         20 | 2006-02-15 04:45:25 |
|     313 | London                     |         20 | 2006-02-15 04:45:25 |
|     383 | Oshawa                     |         20 | 2006-02-15 04:45:25 |
|     430 | Richmond Hill              |         20 | 2006-02-15 04:45:25 |
|     565 | Vancouver                  |         20 | 2006-02-15 04:45:25 |
|     363 | NDjamna                    |         21 | 2006-02-15 04:45:25 |
|      27 | Antofagasta                |         22 | 2006-02-15 04:45:25 |
|     127 | Coquimbo                   |         22 | 2006-02-15 04:45:25 |
|     428 | Rancagua                   |         22 | 2006-02-15 04:45:25 |
|      46 | Baicheng                   |         23 | 2006-02-15 04:45:25 |
|      47 | Baiyin                     |         23 | 2006-02-15 04:45:25 |
|      80 | Binzhou                    |         23 | 2006-02-15 04:45:25 |
|     109 | Changzhou                  |         23 | 2006-02-15 04:45:25 |
|     136 | Datong                     |         23 | 2006-02-15 04:45:25 |
|     139 | Daxian                     |         23 | 2006-02-15 04:45:25 |
|     145 | Dongying                   |         23 | 2006-02-15 04:45:25 |
|     157 | Emeishan                   |         23 | 2006-02-15 04:45:25 |
|     159 | Enshi                      |         23 | 2006-02-15 04:45:25 |
|     166 | Ezhou                      |         23 | 2006-02-15 04:45:25 |
|     174 | Fuyu                       |         23 | 2006-02-15 04:45:25 |
|     175 | Fuzhou                     |         23 | 2006-02-15 04:45:25 |
|     193 | Haining                    |         23 | 2006-02-15 04:45:25 |
|     199 | Hami                       |         23 | 2006-02-15 04:45:25 |
|     207 | Hohhot                     |         23 | 2006-02-15 04:45:25 |
|     210 | Huaian                     |         23 | 2006-02-15 04:45:25 |
|     240 | Jinchang                   |         23 | 2006-02-15 04:45:25 |
|     241 | Jining                     |         23 | 2006-02-15 04:45:25 |
|     242 | Jinzhou                    |         23 | 2006-02-15 04:45:25 |
|     249 | Junan                      |         23 | 2006-02-15 04:45:25 |
|     277 | Korla                      |         23 | 2006-02-15 04:45:25 |
|     291 | Laiwu                      |         23 | 2006-02-15 04:45:25 |
|     293 | Laohekou                   |         23 | 2006-02-15 04:45:25 |
|     298 | Lengshuijiang              |         23 | 2006-02-15 04:45:25 |
|     299 | Leshan                     |         23 | 2006-02-15 04:45:25 |
|     302 | Liaocheng                  |         23 | 2006-02-15 04:45:25 |
|     332 | Meixian                    |         23 | 2006-02-15 04:45:25 |
|     362 | Nanyang                    |         23 | 2006-02-15 04:45:25 |
|     407 | Pingxiang                  |         23 | 2006-02-15 04:45:25 |
|     422 | Qinhuangdao                |         23 | 2006-02-15 04:45:25 |
|     432 | Rizhao                     |         23 | 2006-02-15 04:45:25 |
|     462 | Sanya                      |         23 | 2006-02-15 04:45:25 |
|     468 | Shanwei                    |         23 | 2006-02-15 04:45:25 |
|     469 | Shaoguan                   |         23 | 2006-02-15 04:45:25 |
|     471 | Shenzhen                   |         23 | 2006-02-15 04:45:25 |
|     502 | Suihua                     |         23 | 2006-02-15 04:45:25 |
|     535 | Tianjin                    |         23 | 2006-02-15 04:45:25 |
|     536 | Tiefa                      |         23 | 2006-02-15 04:45:25 |
|     537 | Tieli                      |         23 | 2006-02-15 04:45:25 |
|     540 | Tongliao                   |         23 | 2006-02-15 04:45:25 |
|     574 | Weifang                    |         23 | 2006-02-15 04:45:25 |
|     578 | Xiangfan                   |         23 | 2006-02-15 04:45:25 |
|     579 | Xiangtan                   |         23 | 2006-02-15 04:45:25 |
|     580 | Xintai                     |         23 | 2006-02-15 04:45:25 |
|     581 | Xinxiang                   |         23 | 2006-02-15 04:45:25 |
|     584 | Yantai                     |         23 | 2006-02-15 04:45:25 |
|     587 | Yinchuan                   |         23 | 2006-02-15 04:45:25 |
|     588 | Yingkou                    |         23 | 2006-02-15 04:45:25 |
|     590 | Yuncheng                   |         23 | 2006-02-15 04:45:25 |
|     591 | Yuzhou                     |         23 | 2006-02-15 04:45:25 |
|     592 | Zalantun                   |         23 | 2006-02-15 04:45:25 |
|     594 | Zaoyang                    |         23 | 2006-02-15 04:45:25 |
|     599 | Zhoushan                   |         23 | 2006-02-15 04:45:25 |
|      96 | Buenaventura               |         24 | 2006-02-15 04:45:25 |
|     147 | Dos Quebradas              |         24 | 2006-02-15 04:45:25 |
|     170 | Florencia                  |         24 | 2006-02-15 04:45:25 |
|     405 | Pereira                    |         24 | 2006-02-15 04:45:25 |
|     480 | Sincelejo                  |         24 | 2006-02-15 04:45:25 |
|     487 | Sogamoso                   |         24 | 2006-02-15 04:45:25 |
|     315 | Lubumbashi                 |         25 | 2006-02-15 04:45:25 |
|     348 | Mwene-Ditu                 |         25 | 2006-02-15 04:45:25 |
|     378 | Olomouc                    |         26 | 2006-02-15 04:45:25 |
|     290 | La Romana                  |         27 | 2006-02-15 04:45:25 |
|     450 | San Felipe de Puerto Plata |         27 | 2006-02-15 04:45:25 |
|     460 | Santiago de los Caballeros |         27 | 2006-02-15 04:45:25 |
|     311 | Loja                       |         28 | 2006-02-15 04:45:25 |
|     414 | Portoviejo                 |         28 | 2006-02-15 04:45:25 |
|     434 | Robamba                    |         28 | 2006-02-15 04:45:25 |
|      79 | Bilbays                    |         29 | 2006-02-15 04:45:25 |
|     216 | Idfu                       |         29 | 2006-02-15 04:45:25 |
|     337 | Mit Ghamr                  |         29 | 2006-02-15 04:45:25 |
|     421 | Qalyub                     |         29 | 2006-02-15 04:45:25 |
|     465 | Sawhaj                     |         29 | 2006-02-15 04:45:25 |
|     476 | Shubra al-Khayma           |         29 | 2006-02-15 04:45:25 |
|     530 | Tartu                      |         30 | 2006-02-15 04:45:25 |
|       6 | Addis Abeba                |         31 | 2006-02-15 04:45:25 |
|     545 | Trshavn                    |         32 | 2006-02-15 04:45:25 |
|     387 | Oulu                       |         33 | 2006-02-15 04:45:25 |
|      92 | Brest                      |         34 | 2006-02-15 04:45:25 |
|     297 | Le Mans                    |         34 | 2006-02-15 04:45:25 |
|     543 | Toulon                     |         34 | 2006-02-15 04:45:25 |
|     544 | Toulouse                   |         34 | 2006-02-15 04:45:25 |
|     105 | Cayenne                    |         35 | 2006-02-15 04:45:25 |
|     167 | Faaa                       |         36 | 2006-02-15 04:45:25 |
|     397 | Papeete                    |         36 | 2006-02-15 04:45:25 |
|      54 | Banjul                     |         37 | 2006-02-15 04:45:25 |
|     148 | Duisburg                   |         38 | 2006-02-15 04:45:25 |
|     160 | Erlangen                   |         38 | 2006-02-15 04:45:25 |
|     198 | Halle/Saale                |         38 | 2006-02-15 04:45:25 |
|     325 | Mannheim                   |         38 | 2006-02-15 04:45:25 |
|     439 | Saarbrcken                 |         38 | 2006-02-15 04:45:25 |
|     477 | Siegen                     |         38 | 2006-02-15 04:45:25 |
|     575 | Witten                     |         38 | 2006-02-15 04:45:25 |
|      38 | Athenai                    |         39 | 2006-02-15 04:45:25 |
|     401 | Patras                     |         39 | 2006-02-15 04:45:25 |
|     371 | Nuuk                       |         40 | 2006-02-15 04:45:25 |
|     121 | Citt del Vaticano          |         41 | 2006-02-15 04:45:25 |
|     279 | Kowloon and New Kowloon    |         42 | 2006-02-15 04:45:25 |
|     512 | Szkesfehrvr                |         43 | 2006-02-15 04:45:25 |
|       8 | Adoni                      |         44 | 2006-02-15 04:45:25 |
|       9 | Ahmadnagar                 |         44 | 2006-02-15 04:45:25 |
|      18 | Allappuzha (Alleppey)      |         44 | 2006-02-15 04:45:25 |
|      22 | Ambattur                   |         44 | 2006-02-15 04:45:25 |
|      24 | Amroha                     |         44 | 2006-02-15 04:45:25 |
|      51 | Balurghat                  |         44 | 2006-02-15 04:45:25 |
|      71 | Berhampore (Baharampur)    |         44 | 2006-02-15 04:45:25 |
|      73 | Bhavnagar                  |         44 | 2006-02-15 04:45:25 |
|      74 | Bhilwara                   |         44 | 2006-02-15 04:45:25 |
|      75 | Bhimavaram                 |         44 | 2006-02-15 04:45:25 |
|      76 | Bhopal                     |         44 | 2006-02-15 04:45:25 |
|      77 | Bhusawal                   |         44 | 2006-02-15 04:45:25 |
|      78 | Bijapur                    |         44 | 2006-02-15 04:45:25 |
|     107 | Chandrapur                 |         44 | 2006-02-15 04:45:25 |
|     110 | Chapra                     |         44 | 2006-02-15 04:45:25 |
|     144 | Dhule (Dhulia)             |         44 | 2006-02-15 04:45:25 |
|     164 | Etawah                     |         44 | 2006-02-15 04:45:25 |
|     169 | Firozabad                  |         44 | 2006-02-15 04:45:25 |
|     176 | Gandhinagar                |         44 | 2006-02-15 04:45:25 |
|     191 | Gulbarga                   |         44 | 2006-02-15 04:45:25 |
|     195 | Haldia                     |         44 | 2006-02-15 04:45:25 |
|     197 | Halisahar                  |         44 | 2006-02-15 04:45:25 |
|     208 | Hoshiarpur                 |         44 | 2006-02-15 04:45:25 |
|     211 | Hubli-Dharwad              |         44 | 2006-02-15 04:45:25 |
|     231 | Jaipur                     |         44 | 2006-02-15 04:45:25 |
|     239 | Jhansi                     |         44 | 2006-02-15 04:45:25 |
|     243 | Jodhpur                    |         44 | 2006-02-15 04:45:25 |
|     257 | Kamarhati                  |         44 | 2006-02-15 04:45:25 |
|     261 | Kanchrapara                |         44 | 2006-02-15 04:45:25 |
|     263 | Karnal                     |         44 | 2006-02-15 04:45:25 |
|     264 | Katihar                    |         44 | 2006-02-15 04:45:25 |
|     283 | Kumbakonam                 |         44 | 2006-02-15 04:45:25 |
|     336 | Miraj                      |         44 | 2006-02-15 04:45:25 |
|     346 | Munger (Monghyr)           |         44 | 2006-02-15 04:45:25 |
|     350 | Mysore                     |         44 | 2006-02-15 04:45:25 |
|     354 | Nagaon                     |         44 | 2006-02-15 04:45:25 |
|     395 | Palghat (Palakkad)         |         44 | 2006-02-15 04:45:25 |
|     398 | Parbhani                   |         44 | 2006-02-15 04:45:25 |
|     399 | Pathankot                  |         44 | 2006-02-15 04:45:25 |
|     400 | Patiala                    |         44 | 2006-02-15 04:45:25 |
|     416 | Pudukkottai                |         44 | 2006-02-15 04:45:25 |
|     417 | Pune                       |         44 | 2006-02-15 04:45:25 |
|     418 | Purnea (Purnia)            |         44 | 2006-02-15 04:45:25 |
|     425 | Rae Bareli                 |         44 | 2006-02-15 04:45:25 |
|     426 | Rajkot                     |         44 | 2006-02-15 04:45:25 |
|     427 | Rampur                     |         44 | 2006-02-15 04:45:25 |
|     429 | Ranchi                     |         44 | 2006-02-15 04:45:25 |
|     448 | Sambhal                    |         44 | 2006-02-15 04:45:25 |
|     464 | Satna                      |         44 | 2006-02-15 04:45:25 |
|     473 | Shimoga                    |         44 | 2006-02-15 04:45:25 |
|     475 | Shivapuri                  |         44 | 2006-02-15 04:45:25 |
|     478 | Siliguri (Shiliguri)       |         44 | 2006-02-15 04:45:25 |
|     522 | Tambaram                   |         44 | 2006-02-15 04:45:25 |
|     550 | Udaipur                    |         44 | 2006-02-15 04:45:25 |
|     554 | Uluberia                   |         44 | 2006-02-15 04:45:25 |
|     559 | Uttarpara-Kotrung          |         44 | 2006-02-15 04:45:25 |
|     564 | Valparai                   |         44 | 2006-02-15 04:45:25 |
|     566 | Varanasi (Benares)         |         44 | 2006-02-15 04:45:25 |
|     568 | Vijayawada                 |         44 | 2006-02-15 04:45:25 |
|     582 | Yamuna Nagar               |         44 | 2006-02-15 04:45:25 |
|     117 | Cianjur                    |         45 | 2006-02-15 04:45:25 |
|     118 | Ciomas                     |         45 | 2006-02-15 04:45:25 |
|     119 | Ciparay                    |         45 | 2006-02-15 04:45:25 |
|     184 | Gorontalo                  |         45 | 2006-02-15 04:45:25 |
|     232 | Jakarta                    |         45 | 2006-02-15 04:45:25 |
|     301 | Lhokseumawe                |         45 | 2006-02-15 04:45:25 |
|     318 | Madiun                     |         45 | 2006-02-15 04:45:25 |
|     396 | Pangkal Pinang             |         45 | 2006-02-15 04:45:25 |
|     403 | Pemalang                   |         45 | 2006-02-15 04:45:25 |
|     412 | Pontianak                  |         45 | 2006-02-15 04:45:25 |
|     415 | Probolinggo                |         45 | 2006-02-15 04:45:25 |
|     419 | Purwakarta                 |         45 | 2006-02-15 04:45:25 |
|     509 | Surakarta                  |         45 | 2006-02-15 04:45:25 |
|     532 | Tegal                      |         45 | 2006-02-15 04:45:25 |
|      31 | Arak                       |         46 | 2006-02-15 04:45:25 |
|     162 | Esfahan                    |         46 | 2006-02-15 04:45:25 |
|     265 | Kermanshah                 |         46 | 2006-02-15 04:45:25 |
|     356 | Najafabad                  |         46 | 2006-02-15 04:45:25 |
|     423 | Qomsheh                    |         46 | 2006-02-15 04:45:25 |

In [57]:
!mysql sakila -e "delete from actor where actor_id = '201'"

In [58]:
!mysql sakila -e "select count(*) from actor"

+----------+
| count(*) |
+----------+
|      200 |
+----------+

In [59]:
# this query inserts my name (Misty Peng) into the table of actors as the 201st entry
!mysql sakila -e "insert into actor() values('201', 'MISTY', 'PENG', '2022-02-03 12:55:26')"

In [1]:
# this query updates "Nick Wahlberg" to "Mark Wahlberg"
!mysql sakila -e "update actor set first_name = 'MARK' where actor_id = 2"
!mysql sakila -e "select * from actor limit 3"

+----------+------------+-----------+---------------------+
| actor_id | first_name | last_name | last_update         |
+----------+------------+-----------+---------------------+
|        1 | PENELOPE   | GUINESS   | 2006-02-15 04:34:33 |
|        2 | MARK       | WAHLBERG  | 2022-02-03 20:09:41 |
|        3 | ED         | CHASE     | 2006-02-15 04:34:33 |
+----------+------------+-----------+---------------------+

In [3]:
# delete every film category with a category ID of 6
!mysql sakila -e "delete from film_category where category_id = 6"
!mysql sakila -e "select * from film_category"

+---------+-------------+---------------------+
| film_id | category_id | last_update         |
+---------+-------------+---------------------+
|       2 |          11 | 2006-02-15 05:07:09 |
|       4 |          11 | 2006-02-15 05:07:09 |
|       5 |           8 | 2006-02-15 05:07:09 |
|       6 |           9 | 2006-02-15 05:07:09 |
|       7 |           5 | 2006-02-15 05:07:09 |
|       8 |          11 | 2006-02-15 05:07:09 |
|       9 |          11 | 2006-02-15 05:07:09 |
|      10 |          15 | 2006-02-15 05:07:09 |
|      11 |           9 | 2006-02-15 05:07:09 |
|      12 |          12 | 2006-02-15 05:07:09 |
|      13 |          11 | 2006-02-15 05:07:09 |
|      14 |           4 | 2006-02-15 05:07:09 |
|      15 |           9 | 2006-02-15 05:07:09 |
|      16 |           9 | 2006-02-15 05:07:09 |
|      17 |          12 | 2006-02-15 05:07:09 |
|      18 |           2 | 2006-02-15 05:07:09 |
|      19 |           1 | 2006-02-15 05:07:09 |
|      20 |          12 | 2006-02-15 05:07:09 |
|      21 |           1 | 2006-02-15 05:07:09 |
|      22 |          13 | 2006-02-15 05:07:09 |
|      23 |           2 | 2006-02-15 05:07:09 |
|      24 |          11 | 2006-02-15 05:07:09 |
|      25 |          13 | 2006-02-15 05:07:09 |
|      26 |          14 | 2006-02-15 05:07:09 |
|      27 |          15 | 2006-02-15 05:07:09 |
|      28 |           5 | 2006-02-15 05:07:09 |
|      29 |           1 | 2006-02-15 05:07:09 |
|      30 |          11 | 2006-02-15 05:07:09 |
|      31 |           8 | 2006-02-15 05:07:09 |
|      32 |          13 | 2006-02-15 05:07:09 |
|      33 |           7 | 2006-02-15 05:07:09 |
|      34 |          11 | 2006-02-15 05:07:09 |
|      35 |          11 | 2006-02-15 05:07:09 |
|      36 |           2 | 2006-02-15 05:07:09 |
|      37 |           4 | 2006-02-15 05:07:09 |
|      38 |           1 | 2006-02-15 05:07:09 |
|      39 |          14 | 2006-02-15 05:07:09 |
|      41 |          16 | 2006-02-15 05:07:09 |
|      42 |          15 | 2006-02-15 05:07:09 |
|      43 |           8 | 2006-02-15 05:07:09 |
|      44 |          14 | 2006-02-15 05:07:09 |
|      45 |          13 | 2006-02-15 05:07:09 |
|      46 |          10 | 2006-02-15 05:07:09 |
|      47 |           9 | 2006-02-15 05:07:09 |
|      48 |           3 | 2006-02-15 05:07:09 |
|      49 |          14 | 2006-02-15 05:07:09 |
|      50 |           8 | 2006-02-15 05:07:09 |
|      51 |          12 | 2006-02-15 05:07:09 |
|      52 |           9 | 2006-02-15 05:07:09 |
|      53 |           8 | 2006-02-15 05:07:09 |
|      54 |          12 | 2006-02-15 05:07:09 |
|      55 |          14 | 2006-02-15 05:07:09 |
|      56 |           1 | 2006-02-15 05:07:09 |
|      57 |          16 | 2006-02-15 05:07:09 |
|      59 |           3 | 2006-02-15 05:07:09 |
|      60 |           4 | 2006-02-15 05:07:09 |
|      61 |           7 | 2006-02-15 05:07:09 |
|      63 |           8 | 2006-02-15 05:07:09 |
|      64 |           7 | 2006-02-15 05:07:09 |
|      65 |          11 | 2006-02-15 05:07:09 |
|      66 |           3 | 2006-02-15 05:07:09 |
|      67 |           1 | 2006-02-15 05:07:09 |
|      68 |           3 | 2006-02-15 05:07:09 |
|      69 |          14 | 2006-02-15 05:07:09 |
|      70 |           2 | 2006-02-15 05:07:09 |
|      71 |           8 | 2006-02-15 05:07:09 |
|      73 |          14 | 2006-02-15 05:07:09 |
|      74 |          12 | 2006-02-15 05:07:09 |
|      75 |          16 | 2006-02-15 05:07:09 |
|      76 |          12 | 2006-02-15 05:07:09 |
|      77 |          13 | 2006-02-15 05:07:09 |
|      78 |           2 | 2006-02-15 05:07:09 |
|      79 |           7 | 2006-02-15 05:07:09 |
|      80 |           8 | 2006-02-15 05:07:09 |
|      81 |          14 | 2006-02-15 05:07:09 |
|      82 |           8 | 2006-02-15 05:07:09 |
|      83 |           8 | 2006-02-15 05:07:09 |
|      84 |          16 | 2006-02-15 05:07:09 |
|      86 |          12 | 2006-02-15 05:07:09 |
|      87 |          16 | 2006-02-15 05:07:09 |
|      88 |          16 | 2006-02-15 05:07:09 |
|      89 |           2 | 2006-02-15 05:07:09 |
|      90 |          13 | 2006-02-15 05:07:09 |
|      91 |           4 | 2006-02-15 05:07:09 |
|      92 |          11 | 2006-02-15 05:07:09 |
|      93 |          13 | 2006-02-15 05:07:09 |
|      94 |           8 | 2006-02-15 05:07:09 |
|      95 |          13 | 2006-02-15 05:07:09 |
|      96 |          13 | 2006-02-15 05:07:09 |
|      97 |           1 | 2006-02-15 05:07:09 |
|      98 |           7 | 2006-02-15 05:07:09 |
|      99 |           5 | 2006-02-15 05:07:09 |
|     100 |           9 | 2006-02-15 05:07:09 |
|     102 |          15 | 2006-02-15 05:07:09 |
|     103 |          16 | 2006-02-15 05:07:09 |
|     104 |           9 | 2006-02-15 05:07:09 |
|     105 |           1 | 2006-02-15 05:07:09 |
|     106 |          10 | 2006-02-15 05:07:09 |
|     107 |           7 | 2006-02-15 05:07:09 |
|     108 |          13 | 2006-02-15 05:07:09 |
|     109 |          13 | 2006-02-15 05:07:09 |
|     110 |           3 | 2006-02-15 05:07:09 |
|     111 |           1 | 2006-02-15 05:07:09 |
|     112 |           9 | 2006-02-15 05:07:09 |
|     113 |          15 | 2006-02-15 05:07:09 |
|     114 |          14 | 2006-02-15 05:07:09 |
|     115 |           1 | 2006-02-15 05:07:09 |
|     116 |           4 | 2006-02-15 05:07:09 |
|     117 |          10 | 2006-02-15 05:07:09 |
|     118 |           2 | 2006-02-15 05:07:09 |
|     119 |           5 | 2006-02-15 05:07:09 |
|     120 |          15 | 2006-02-15 05:07:09 |
|     121 |           2 | 2006-02-15 05:07:09 |
|     122 |          11 | 2006-02-15 05:07:09 |
|     123 |          16 | 2006-02-15 05:07:09 |
|     124 |           3 | 2006-02-15 05:07:09 |
|     125 |          16 | 2006-02-15 05:07:09 |
|     126 |           1 | 2006-02-15 05:07:09 |
|     127 |           5 | 2006-02-15 05:07:09 |
|     128 |           9 | 2006-02-15 05:07:09 |
|     130 |           1 | 2006-02-15 05:07:09 |
|     131 |           4 | 2006-02-15 05:07:09 |
|     132 |          14 | 2006-02-15 05:07:09 |
|     133 |          12 | 2006-02-15 05:07:09 |
|     134 |           2 | 2006-02-15 05:07:09 |
|     135 |          15 | 2006-02-15 05:07:09 |
|     136 |          13 | 2006-02-15 05:07:09 |
|     137 |          14 | 2006-02-15 05:07:09 |
|     138 |          14 | 2006-02-15 05:07:09 |
|     139 |           8 | 2006-02-15 05:07:09 |
|     140 |          14 | 2006-02-15 05:07:09 |
|     141 |          10 | 2006-02-15 05:07:09 |
|     143 |           7 | 2006-02-15 05:07:09 |
|     144 |          13 | 2006-02-15 05:07:09 |
|     145 |           8 | 2006-02-15 05:07:09 |
|     146 |           7 | 2006-02-15 05:07:09 |
|     147 |           8 | 2006-02-15 05:07:09 |
|     148 |           9 | 2006-02-15 05:07:09 |
|     149 |           3 | 2006-02-15 05:07:09 |
|     151 |          14 | 2006-02-15 05:07:09 |
|     152 |           3 | 2006-02-15 05:07:09 |
|     153 |          14 | 2006-02-15 05:07:09 |
|     154 |           2 | 2006-02-15 05:07:09 |
|     155 |          13 | 2006-02-15 05:07:09 |
|     157 |           3 | 2006-02-15 05:07:09 |
|     158 |          12 | 2006-02-15 05:07:09 |
|     159 |           5 | 2006-02-15 05:07:09 |
|     160 |           2 | 2006-02-15 05:07:09 |
|     161 |          12 | 2006-02-15 05:07:09 |
|     162 |           1 | 2006-02-15 05:07:09 |
|     163 |          13 | 2006-02-15 05:07:09 |
|     165 |          14 | 2006-02-15 05:07:09 |
|     166 |           4 | 2006-02-15 05:07:09 |
|     167 |          16 | 2006-02-15 05:07:09 |
|     168 |           3 | 2006-02-15 05:07:09 |
|     169 |          16 | 2006-02-15 05:07:09 |
|     170 |           9 | 2006-02-15 05:07:09 |
|     171 |          11 | 2006-02-15 05:07:09 |
|     172 |           7 | 2006-02-15 05:07:09 |
|     173 |           7 | 2006-02-15 05:07:09 |
|     174 |          12 | 2006-02-15 05:07:09 |
|     175 |           8 | 2006-02-15 05:07:09 |
|     176 |          15 | 2006-02-15 05:07:09 |
|     177 |          14 | 2006-02-15 05:07:09 |
|     178 |           5 | 2006-02-15 05:07:09 |
|     179 |           7 | 2006-02-15 05:07:09 |
|     180 |           4 | 2006-02-15 05:07:09 |
|     181 |          16 | 2006-02-15 05:07:09 |
|     182 |           5 | 2006-02-15 05:07:09 |
|     183 |           8 | 2006-02-15 05:07:09 |
|     184 |           4 | 2006-02-15 05:07:09 |
|     185 |           9 | 2006-02-15 05:07:09 |
|     186 |           7 | 2006-02-15 05:07:09 |
|     187 |          15 | 2006-02-15 05:07:09 |
|     188 |           5 | 2006-02-15 05:07:09 |
|     189 |          10 | 2006-02-15 05:07:09 |
|     190 |           4 | 2006-02-15 05:07:09 |
|     191 |           3 | 2006-02-15 05:07:09 |
|     192 |           9 | 2006-02-15 05:07:09 |
|     193 |           2 | 2006-02-15 05:07:09 |
|     194 |           1 | 2006-02-15 05:07:09 |
|     195 |          14 | 2006-02-15 05:07:09 |
|     196 |           4 | 2006-02-15 05:07:09 |
|     197 |          15 | 2006-02-15 05:07:09 |
|     198 |           9 | 2006-02-15 05:07:09 |
|     200 |          10 | 2006-02-15 05:07:09 |
|     201 |           9 | 2006-02-15 05:07:09 |
|     202 |           5 | 2006-02-15 05:07:09 |
|     203 |          14 | 2006-02-15 05:07:09 |
|     204 |           7 | 2006-02-15 05:07:09 |
|     205 |           1 | 2006-02-15 05:07:09 |
|     207 |           9 | 2006-02-15 05:07:09 |
|     208 |           2 | 2006-02-15 05:07:09 |
|     209 |           7 | 2006-02-15 05:07:09 |
|     210 |           1 | 2006-02-15 05:07:09 |
|     211 |          10 | 2006-02-15 05:07:09 |
|     212 |           1 | 2006-02-15 05:07:09 |
|     213 |           8 | 2006-02-15 05:07:09 |
|     214 |           3 | 2006-02-15 05:07:09 |
|     215 |          10 | 2006-02-15 05:07:09 |
|     216 |          13 | 2006-02-15 05:07:09 |
|     217 |          10 | 2006-02-15 05:07:09 |
|     218 |           7 | 2006-02-15 05:07:09 |
|     220 |          12 | 2006-02-15 05:07:09 |
|     222 |          11 | 2006-02-15 05:07:09 |
|     223 |           2 | 2006-02-15 05:07:09 |
|     224 |          16 | 2006-02-15 05:07:09 |
|     225 |           7 | 2006-02-15 05:07:09 |
|     226 |          13 | 2006-02-15 05:07:09 |
|     227 |          10 | 2006-02-15 05:07:09 |
|     228 |           4 | 2006-02-15 05:07:09 |
|     229 |           1 | 2006-02-15 05:07:09 |
|     230 |           7 | 2006-02-15 05:07:09 |
|     231 |           8 | 2006-02-15 05:07:09 |
|     232 |          10 | 2006-02-15 05:07:09 |
|     233 |          16 | 2006-02-15 05:07:09 |
|     234 |          14 | 2006-02-15 05:07:09 |
|     235 |          14 | 2006-02-15 05:07:09 |
|     236 |          10 | 2006-02-15 05:07:09 |
|     237 |          15 | 2006-02-15 05:07:09 |
|     238 |           3 | 2006-02-15 05:07:09 |
|     239 |           2 | 2006-02-15 05:07:09 |
|     240 |          14 | 2006-02-15 05:07:09 |
|     241 |           2 | 2006-02-15 05:07:09 |
|     242 |           5 | 2006-02-15 05:07:09 |
|     243 |           2 | 2006-02-15 05:07:09 |
|     244 |          12 | 2006-02-15 05:07:09 |
|     245 |           2 | 2006-02-15 05:07:09 |
|     246 |           9 | 2006-02-15 05:07:09 |
|     247 |           5 | 2006-02-15 05:07:09 |
|     249 |           4 | 2006-02-15 05:07:09 |
|     250 |           1 | 2006-02-15 05:07:09 |
|     251 |          13 | 2006-02-15 05:07:09 |
|     252 |           1 | 2006-02-15 05:07:09 |
|     253 |           1 | 2006-02-15 05:07:09 |
|     254 |          15 | 2006-02-15 05:07:09 |
|     255 |          12 | 2006-02-15 05:07:09 |
|     256 |          15 | 2006-02-15 05:07:09 |
|     257 |          16 | 2006-02-15 05:07:09 |
|     258 |          11 | 2006-02-15 05:07:09 |
|     259 |           2 | 2006-02-15 05:07:09 |
|     260 |          15 | 2006-02-15 05:07:09 |
|     262 |           8 | 2006-02-15 05:07:09 |
|     263 |          15 | 2006-02-15 05:07:09 |
|     264 |          10 | 2006-02-15 05:07:09 |
|     265 |           5 | 2006-02-15 05:07:09 |
|     266 |           4 | 2006-02-15 05:07:09 |
|     267 |          13 | 2006-02-15 05:07:09 |
|     268 |           2 | 2006-02-15 05:07:09 |
|     269 |           8 | 2006-02-15 05:07:09 |
|     270 |          13 | 2006-02-15 05:07:09 |
|     271 |           1 | 2006-02-15 05:07:09 |
|     272 |           7 | 2006-02-15 05:07:09 |
|     273 |           8 | 2006-02-15 05:07:09 |
|     275 |          11 | 2006-02-15 05:07:09 |
|     276 |           5 | 2006-02-15 05:07:09 |
|     277 |          11 | 2006-02-15 05:07:09 |
|     278 |          12 | 2006-02-15 05:07:09 |
|     279 |          15 | 2006-02-15 05:07:09 |
|     280 |           3 | 2006-02-15 05:07:09 |
|     281 |          10 | 2006-02-15 05:07:09 |
|     282 |           7 | 2006-02-15 05:07:09 |
|     283 |          13 | 2006-02-15 05:07:09 |
|     284 |          12 | 2006-02-15 05:07:09 |
|     285 |          14 | 2006-02-15 05:07:09 |
|     286 |          16 | 2006-02-15 05:07:09 |
|     287 |           1 | 2006-02-15 05:07:09 |
|     288 |          16 | 2006-02-15 05:07:09 |
|     289 |          13 | 2006-02-15 05:07:09 |
|     290 |           9 | 2006-02-15 05:07:09 |
|     291 |          15 | 2006-02-15 05:07:09 |
|     292 |           1 | 2006-02-15 05:07:09 |
|     293 |          15 | 2006-02-15 05:07:09 |
|     294 |          16 | 2006-02-15 05:07:09 |
|     296 |          14 | 2006-02-15 05:07:09 |
|     297 |           4 | 2006-02-15 05:07:09 |
|     298 |          14 | 2006-02-15 05:07:09 |
|     299 |          16 | 2006-02-15 05:07:09 |
|     300 |           2 | 2006-02-15 05:07:09 |
|     301 |          11 | 2006-02-15 05:07:09 |
|     302 |          10 | 2006-02-15 05:07:09 |
|     303 |           1 | 2006-02-15 05:07:09 |
|     304 |           3 | 2006-02-15 05:07:09 |
|     305 |          13 | 2006-02-15 05:07:09 |
|     306 |          10 | 2006-02-15 05:07:09 |
|     307 |          16 | 2006-02-15 05:07:09 |
|     308 |           5 | 2006-02-15 05:07:09 |
|     309 |           8 | 2006-02-15 05:07:09 |
|     310 |          10 | 2006-02-15 05:07:09 |
|     311 |           9 | 2006-02-15 05:07:09 |
|     312 |          14 | 2006-02-15 05:07:09 |
|     313 |          11 | 2006-02-15 05:07:09 |
|     314 |           2 | 2006-02-15 05:07:09 |
|     315 |           8 | 2006-02-15 05:07:09 |
|     316 |          10 | 2006-02-15 05:07:09 |
|     317 |           5 | 2006-02-15 05:07:09 |
|     318 |           1 | 2006-02-15 05:07:09 |
|     319 |          14 | 2006-02-15 05:07:09 |
|     320 |          13 | 2006-02-15 05:07:09 |
|     321 |          13 | 2006-02-15 05:07:09 |
|     322 |          15 | 2006-02-15 05:07:09 |
|     323 |          15 | 2006-02-15 05:07:09 |
|     324 |           5 | 2006-02-15 05:07:09 |
|     325 |           2 | 2006-02-15 05:07:09 |
|     326 |           2 | 2006-02-15 05:07:09 |
|     327 |           1 | 2006-02-15 05:07:09 |
|     328 |           3 | 2006-02-15 05:07:09 |
|     329 |           1 | 2006-02-15 05:07:09 |
|     330 |           2 | 2006-02-15 05:07:09 |
|     331 |          10 | 2006-02-15 05:07:09 |
|     332 |           5 | 2006-02-15 05:07:09 |
|     333 |          12 | 2006-02-15 05:07:09 |
|     334 |          11 | 2006-02-15 05:07:09 |
|     335 |           5 | 2006-02-15 05:07:09 |
|     337 |           9 | 2006-02-15 05:07:09 |
|     338 |          14 | 2006-02-15 05:07:09 |
|     339 |          16 | 2006-02-15 05:07:09 |
|     340 |          13 | 2006-02-15 05:07:09 |
|     341 |           4 | 2006-02-15 05:07:09 |
|     342 |          16 | 2006-02-15 05:07:09 |
|     343 |           3 | 2006-02-15 05:07:09 |
|     344 |           3 | 2006-02-15 05:07:09 |
|     345 |           8 | 2006-02-15 05:07:09 |
|     346 |           4 | 2006-02-15 05:07:09 |
|     347 |          16 | 2006-02-15 05:07:09 |
|     348 |           8 | 2006-02-15 05:07:09 |
|     349 |           2 | 2006-02-15 05:07:09 |
|     350 |          14 | 2006-02-15 05:07:09 |
|     351 |          11 | 2006-02-15 05:07:09 |
|     352 |          10 | 2006-02-15 05:07:09 |
|     353 |           9 | 2006-02-15 05:07:09 |
|     354 |           3 | 2006-02-15 05:07:09 |
|     355 |           2 | 2006-02-15 05:07:09 |
|     356 |           3 | 2006-02-15 05:07:09 |
|     357 |           4 | 2006-02-15 05:07:09 |
|     358 |           4 | 2006-02-15 05:07:09 |
|     359 |           8 | 2006-02-15 05:07:09 |
|     360 |           1 | 2006-02-15 05:07:09 |
|     361 |          15 | 2006-02-15 05:07:09 |
|     362 |          10 | 2006-02-15 05:07:09 |
|     363 |          12 | 2006-02-15 05:07:09 |
|     364 |          13 | 2006-02-15 05:07:09 |
|     365 |           5 | 2006-02-15 05:07:09 |
|     366 |           7 | 2006-02-15 05:07:09 |
|     367 |          14 | 2006-02-15 05:07:09 |
|     368 |           7 | 2006-02-15 05:07:09 |
|     369 |          14 | 2006-02-15 05:07:09 |
|     370 |           3 | 2006-02-15 05:07:09 |
|     371 |           1 | 2006-02-15 05:07:09 |
|     372 |          15 | 2006-02-15 05:07:09 |
|     373 |           3 | 2006-02-15 05:07:09 |
|     374 |          14 | 2006-02-15 05:07:09 |
|     375 |           1 | 2006-02-15 05:07:09 |
|     376 |           9 | 2006-02-15 05:07:09 |
|     377 |           8 | 2006-02-15 05:07:09 |
|     378 |          12 | 2006-02-15 05:07:09 |
|     379 |           7 | 2006-02-15 05:07:09 |
|     380 |           9 | 2006-02-15 05:07:09 |
|     381 |          10 | 2006-02-15 05:07:09 |
|     382 |          10 | 2006-02-15 05:07:09 |
|     383 |          15 | 2006-02-15 05:07:09 |
|     384 |          12 | 2006-02-15 05:07:09 |
|     385 |           5 | 2006-02-15 05:07:09 |
|     386 |          16 | 2006-02-15 05:07:09 |
|     387 |          10 | 2006-02-15 05:07:09 |
|     388 |           5 | 2006-02-15 05:07:09 |
|     389 |          15 | 2006-02-15 05:07:09 |
|     390 |          14 | 2006-02-15 05:07:09 |
|     391 |           8 | 2006-02-15 05:07:09 |
|     392 |           3 | 2006-02-15 05:07:09 |
|     394 |          14 | 2006-02-15 05:07:09 |
|     395 |           1 | 2006-02-15 05:07:09 |
|     396 |           7 | 2006-02-15 05:07:09 |
|     397 |          14 | 2006-02-15 05:07:09 |
|     398 |          12 | 2006-02-15 05:07:09 |
|     399 |           9 | 2006-02-15 05:07:09 |
|     401 |           7 | 2006-02-15 05:07:09 |
|     402 |           2 | 2006-02-15 05:07:09 |
|     403 |           7 | 2006-02-15 05:07:09 |
|     404 |           5 | 2006-02-15 05:07:09 |
|     405 |          16 | 2006-02-15 05:07:09 |
|     406 |          10 | 2006-02-15 05:07:09 |
|     408 |          10 | 2006-02-15 05:07:09 |
|     409 |           3 | 2006-02-15 05:07:09 |
|     410 |           5 | 2006-02-15 05:07:09 |
|     411 |          12 | 2006-02-15 05:07:09 |
|     413 |           5 | 2006-02-15 05:07:09 |
|     414 |           9 | 2006-02-15 05:07:09 |
|     415 |          11 | 2006-02-15 05:07:09 |
|     416 |           9 | 2006-02-15 05:07:09 |
|     417 |           1 | 2006-02-15 05:07:09 |
|     418 |           7 | 2006-02-15 05:07:09 |
|     419 |           8 | 2006-02-15 05:07:09 |
|     420 |          15 | 2006-02-15 05:07:09 |
|     421 |           9 | 2006-02-15 05:07:09 |
|     422 |          14 | 2006-02-15 05:07:09 |
|     423 |           3 | 2006-02-15 05:07:09 |
|     424 |           3 | 2006-02-15 05:07:09 |
|     425 |           4 | 2006-02-15 05:07:09 |
|     426 |          12 | 2006-02-15 05:07:09 |
|     428 |           8 | 2006-02-15 05:07:09 |
|     429 |          15 | 2006-02-15 05:07:09 |
|     430 |           2 | 2006-02-15 05:07:09 |
|     431 |           9 | 2006-02-15 05:07:09 |
|     432 |           4 | 2006-02-15 05:07:09 |
|     433 |           2 | 2006-02-15 05:07:09 |
|     434 |          16 | 2006-02-15 05:07:09 |
|     435 |           9 | 2006-02-15 05:07:09 |
|     436 |          13 | 2006-02-15 05:07:09 |
|     437 |           8 | 2006-02-15 05:07:09 |
|     438 |          10 | 2006-02-15 05:07:09 |
|     439 |           7 | 2006-02-15 05:07:09 |
|     440 |           9 | 2006-02-15 05:07:09 |